# Generated by Django 4.1.7 on 2023-04-18 13:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('image', models.CharField(default='Image', max_length=500)),
                ('score', models.DecimalField(decimal_places=1, max_digits=3)),
                ('description', models.TextField(default='SomeDescription')),
                ('book_type', models.CharField(choices=[('Манга', 'Manga'), ('Манхва', 'Manhwa'), ('Маньхуа', 'Manhua')], default='Манга', max_length=10)),
                ('release_date', models.IntegerField()),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('chapters', models.IntegerField(default=0)),
                ('link', models.CharField(default='SomeLink', max_length=300)),
                ('book', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='sources', to='books.book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='genres', to='books.genre'),
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='books.tag'),
        ),
    ]
